#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bleach
Version  : 3.0.2
Release  : 29
URL      : https://files.pythonhosted.org/packages/ae/31/680afc7d44040004296a2d8f0584983c2f2386448cd9d0964197e6c1160e/bleach-3.0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/ae/31/680afc7d44040004296a2d8f0584983c2f2386448cd9d0964197e6c1160e/bleach-3.0.2.tar.gz
Summary  : An easy safelist-based HTML-sanitizing tool.
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: bleach-license = %{version}-%{release}
Requires: bleach-python = %{version}-%{release}
Requires: bleach-python3 = %{version}-%{release}
Requires: six
Requires: webencodings
BuildRequires : buildreq-distutils3
BuildRequires : html5lib
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : webencodings

%description
Bleach
        ======

%package license
Summary: license components for the bleach package.
Group: Default

%description license
license components for the bleach package.


%package python
Summary: python components for the bleach package.
Group: Default
Requires: bleach-python3 = %{version}-%{release}

%description python
python components for the bleach package.


%package python3
Summary: python3 components for the bleach package.
Group: Default
Requires: python3-core

%description python3
python3 components for the bleach package.


%prep
%setup -q -n bleach-3.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540929957
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bleach
cp LICENSE %{buildroot}/usr/share/package-licenses/bleach/LICENSE
cp bleach/_vendor/html5lib-1.0.1.dist-info/LICENSE.txt %{buildroot}/usr/share/package-licenses/bleach/bleach__vendor_html5lib-1.0.1.dist-info_LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bleach/LICENSE
/usr/share/package-licenses/bleach/bleach__vendor_html5lib-1.0.1.dist-info_LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
